name: Deploy to Temporary EC2

on:
  workflow_run:
    workflows: ["Nightly Build"]
    types:
      - success
  workflow_dispatch:

env:
  MyEC2KeyPair: |
    ${{ secrets.MyEC2KeyPair }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: ${{ secrets.AWS_REGION }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Source"

      - name: Setting up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$MyEC2KeyPair" > ~/.ssh/MyEC2KeyPair.pem
          chmod 400 ~/.ssh/MyEC2KeyPair.pem

      - name: Launching temporary EC2
        run: |
         aws ec2 run-instances \
           --image-id ami-05b10e08d247fb927 --count 1 \
           --instance-type t2.micro --key-name MyEC2KeyPair \
           --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=temp_EC2}]'
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Fetch IP of EC2
        run: |
          export IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=temp_EC2" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo $IP
          echo "IP=$IP" >> $GITHUB_ENV
      - name: Copying test, init.sql, docker-compose files from source repo to EC2
        run: |
          echo $IP
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no test/test_2.sh ec2-user@$IP:~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no init.sql ec2-user@$IP:~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no docker-compose.ec2.yml ec2-user@$IP:~/
        

      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Infra"

      - name: Copy sh files
        run: |
          echo $IP
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./docker_build.sh ec2-user@$IP:~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./docker_setup.sh ec2-user@$IP:~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./ecr_steps.sh ec2-user@$IP:~/
          
      - name: ssh to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/MyEC2KeyPair.pem ec2-user@"$IP" << 'EOF'
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
            echo $AWS_ACCESS_KEY_ID
            echo "Docker setup"
            bash docker_setup.sh
            echo "working dir test"
            echo pwd
            echo "ECR"
            bash ecr_steps.sh
            echo "docker build"
            exit
          EOF

      - name: Integration_tests
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/MyEC2KeyPair.pem ec2-user@"$IP" << 'EOF'
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
            export FRONTEND_TIMESTAMP=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E '^.*:frontend_' | awk -F: '{print $2}' | sort -V | head -n 1)
            export BACKEND_TIMESTAMP=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E '^.*:backend_' | awk -F: '{print $2}' | sort -V | head -n 1)
            bash test_2.sh
            if [ $? -ne 0 ]; then
              echo "Tests failed"
              aws ecr batch-delete-image \
                --repository-name midterm/ecr_1 \
                --image-ids imageTag=$BACKEND_TIMESTAMP
          
              aws ecr batch-delete-image \
                --repository-name midterm/ecr_1 \
                --image-ids imageTag=$FRONTEND_TIMESTAMP
            else
              echo "Tests pass"
              sudo docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:$BACKEND_TIMESTAMP
              sudo docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:$FRONTEND_TIMESTAMP
            fi
          EOF
          
          
          
