name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Source"

     #Build docker image for backend
      - name: build docker image for backend
        run: |
          docker compose up --build -d backend

     #Build docker image for frontend
      - name: build docker image for frontend
        run: |
          docker compose up --build -d frontend    

     #include code to perform unit and integration tests

     #Get access to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker images with timestamp
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          SET AWS_ACCOUNT_ID = 343830488876
          docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1/backend:$TIMESTAMP
          docker tag frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1/frontend:$TIMESTAMP

      - name: Push images to ECR
        if: success()
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1/backend:$TIMESTAMP
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1/frontend:$TIMESTAMP
