name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

  #push:
    #branches:
     #- main

env:
  MyEC2KeyPair: |
    ${{ secrets.MyEC2KeyPair }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: ${{ secrets.AWS_REGION }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Source"

     #Build docker image for backend
      - name: build docker image for backend
        run: |
          docker compose up --build -d backend
          docker tag cs686_midterm_source/backend:latest backend:latest

     #Build docker image for frontend
      - name: build docker image for frontend
        run: |
          docker compose up --build -d frontend
          docker tag cs686_midterm_source/frontend:latest frontend:latest

     #include code to perform unit and integration tests

     #Get access to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and Push Docker images with timestamp
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          BACKEND_TIMESTAMP="backend_"$TIMESTAMP
          FRONTEND_TIMESTAMP="frontend_"$TIMESTAMP
          docker tag backend:latest 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1:$BACKEND_TIMESTAMP
          docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1:$BACKEND_TIMESTAMP
          docker tag frontend:latest 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1:$FRONTEND_TIMESTAMP
          docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1:$FRONTEND_TIMESTAMP

      - name: Terminating containers locally
        run: |
          docker compose down -v

      

          
          
          

      #- name: Push images to ECR
      #  if: success()
      #  run: |
      #    docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1/backend:$TIMESTAMP
      #    docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1/frontend:$TIMESTAMP
