name: QA Deployment

on:
  workflow_run:
    workflows: [ "Deploy to Temporary EC2" ]
    types:
      - success
  workflow_dispatch:

env:
  MyEC2KeyPair: |
    ${{ secrets.MyEC2KeyPair }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: ${{ secrets.AWS_REGION }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Infra"

      - name: Setting up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$MyEC2KeyPair" > ~/.ssh/MyEC2KeyPair.pem
          chmod 400 ~/.ssh/MyEC2KeyPair.pem

      - name: Get IP of QA EC2
        run: |
          source ./qa/ec2_config.env
          echo $INSTANCE_NAME
          echo $IP
          echo "IP=$IP" >> $GITHUB_ENV

      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Infra"

      - name: Copy sh files
        run: |
          echo $IP
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./qa/docker_setup.sh ec2-user@"$IP":~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./qa/pull_images.sh ec2-user@"$IP":~/

      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Source"

      - name: scp files from dev to QA
        run: |
          echo $IP
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./test/test_2.sh ec2-user@"$IP":~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no init.sql ec2-user@"$IP":~/
          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no docker-compose.qa.yml ec2-user@"$IP":~/

      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: "likhithabz55/CS686_Midterm_Infra"

      - name: Connect to QA EC2
        run : |
          source ./qa/ec2_config.env
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/MyEC2KeyPair.pem ec2-user@"$IP" << 'EOF'
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
            export DOCKER_CONFIG=$HOME/.docker
            
            echo "Docker setup"
            chmod +x docker_setup.sh
            ./docker_setup.sh
            newgrp docker
            echo "Docker installed"
            
            echo "ECR"
            chmod +x pull_images.sh
            ./pull_images.sh
            exit
          EOF
            
            
            
            
            


